# Generated by Django 4.1.6 on 2023-02-18 12:23

from django.db import migrations

from images.models import Size
from plans.models import SubscriptionPlan


def create_subscription_plans(apps, schema_editor):
    """Create 3 initial subscription plans to populate db"""
    height_200 = Size.objects.get(height=200)
    height_400 = Size.objects.get(height=400)

    plans = [
        {"plan_name": "Basic",
         "thumbnail_sizes": [height_200],
         "original_url": False,
         "temporary_url": False},
        {"plan_name": "Premium",
         "thumbnail_sizes": [height_200, height_400],
         "original_url": True,
         "temporary_url": False},
        {"plan_name": "Enterprise",
         "thumbnail_sizes": [height_200, height_400],
         "original_url": True,
         "temporary_url": True},
    ]

    for plan in plans:
        subscription_plan = SubscriptionPlan.objects.create(
            plan_name=plan["plan_name"],
            original_url=plan["original_url"],
            temporary_url=plan["temporary_url"],
        )

        subscription_plan.save()
        for size in plan["thumbnail_sizes"]:
            subscription_plan.thumbnail_sizes.add(size)


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subscription_plans)
    ]
