# Generated by Django 4.1.6 on 2023-02-13 20:37

from django.db import migrations, models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.FileField(upload_to='pictures', validators=[images.validators.validate_file_type]),
        ),
    ]
