# Generated by Django 4.1.6 on 2023-02-18 12:18

from django.db import migrations

from images.models import Size


def create_sizes(apps, schema_editor):
    """Create 2 initial thumbnail sizes to populate db"""
    heights = [200, 400]
    for height in heights:
        size = Size.objects.create(height=height)
        size.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_size_thumbnail'),
    ]

    operations = [
        migrations.RunPython(create_sizes)
    ]
