# Generated by Django 4.1.6 on 2023-02-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_custom_populate_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32)),
                ('duration', models.DateTimeField()),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.picture')),
            ],
        ),
    ]
